.github/workflows/build_and_push.yml, .github/workflows/scripts/migrate.sh, README.md, terragrunt/aws/api/iam.tf, terragrunt/aws/api/lambda.tf
Deploy api lambda and updated migrate script that waits for lambda to be a ready state before trying to perform database migrations.
=> feat: api lambda

api/api_gateway/api.py, api/api_gateway/routers/ops.py, api/api_gateway/routers/web_socket.py, api/database/db.py, api/main.py, api/requirements.txt, api/tests/api_gateway/test_web_socket.py, api/tests/test_main.py, terragrunt/aws/api/api_gateway.tf, terragrunt/aws/api/api_gateway_websocket.tf, terragrunt/aws/api/cloudwatch_log.tf, terragrunt/aws/api/ecr.tf, terragrunt/aws/api/iam.tf, terragrunt/aws/api/kms.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/vpc.tf, terragrunt/aws/api/waf.tf, terragrunt/env/terragrunt.hcl
Deploy apigatewayv2 websocket proxy and add experimental websocket functionality to the api.
upload file &#8594; connect to websocket & provide scan id &#8594; web socket server responds with file status
=> feat: apigateway for websocket connections

api/api_gateway/routers/scans.py, api/models/Scan.py, api/tests/api_gateway/test_scans.py
=> fix: scan verdict nows matches assemblyline

api/Makefile, api/api_gateway/routers/scans.py, api/boto3wrapper/wrapper.py, api/storage/storage.py, api/tests/api_gateway/test_scans.py, api/tests/storage/test_storage.py
Save uploaded files to s3 for processing by a future scan queue
=> feat: save file to s3 for async processing

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, terragrunt/aws/hosted_zone/hosted_zone.tf, terragrunt/aws/hosted_zone/inputs.tf, terragrunt/aws/hosted_zone/outputs.tf, terragrunt/env/hosted_zone/terragrunt.hcl
=> feat: scan-files hosted zone

terragrunt/aws/scan_queue/iam.tf
=> feat: add missing iam policy

terragrunt/aws/scan_queue/cloudwatch_events.tf
=> feat: cleanup lock table when a state machine execution fails

terragrunt/aws/scan_queue/iam.tf
=> feat: allow eventbridge to assume the scanqueue role

api/Makefile, api/assemblyline/assemblyline.py, api/main.py, api/tests/assemblyline/test_assemblyline.py, api/tests/test_main.py, terragrunt/aws/api/lambda.tf, terragrunt/env/scan_queue/state-machines/scan-queue.json
=> feat: retry scans that haven't completed in 24 hours

api/assemblyline/assemblyline.py, api/tests/assemblyline/test_assemblyline.py
=> fix: select empty verdict instead of in_progress

api/assemblyline/assemblyline.py, api/main.py, api/tests/assemblyline/test_assemblyline.py, api/tests/test_main.py, terragrunt/env/scan_queue/state-machines/scan-queue.json, terragrunt/env/scan_queue/terragrunt.hcl
=> feat: send files to high priority rate limited submit queue

api/assemblyline/assemblyline.py, api/tests/assemblyline/test_assemblyline.py
=> fix: flag scans with missing file as an error

.github/workflows/build_and_push.yml
send AWS lambda function update to /dev/null
=> fix: send AWS lambda function update to /dev/null

api/main.py, api/requirements_dev.txt, api/tests/test_main.py
minor tweak to wait for results from assemblyline before clearing state machine lock.
=> fix: dont clear lock if no results

.github/workflows/build_and_push.yml, .github/workflows/ci_build_continers.yml, .github/workflows/generate_sbom.yml, api/Dockerfile
* Generate an SBOM for the `api` Docker image.
* Update `api` SBOM generation to use action defaults.
* cds-snc/platform-sre-security-support#94
=> feat: generate SBOM for api Docker image

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml
Removes AWS credentials and login. Adds OIDC in.
=> Add OIDC AWS login in TFapply and TFplan actions

.github/workflows/build_and_push.yml
Test the lambda service after new images are deployed to ensure that the service is healthy
=> feat: perform ci healthchecks when a new lambda is deployed

.github/workflows/bandit_security_scan.yml, .github/workflows/build_and_push.yml, .github/workflows/ci_build_continers.yml, .github/workflows/ci_code.yml, .github/workflows/generate_sbom.yml, .github/workflows/labels.yml, .github/workflows/s3-backup.yml, .github/workflows/scripts.yml, .github/workflows/terraform-security-scan.yml, .github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, renovate.json
Ensuring GitHub Actions are pinned to a SHA as well as scheduling renovate dependency update PRs to be created once a week
=> feat: pin github actions to shas

.github/workflows/bandit_security_scan.yml, .github/workflows/build_and_push.yml, .github/workflows/ci_build_continers.yml, .github/workflows/ci_code.yml, .github/workflows/generate_sbom.yml, .github/workflows/labels.yml, .github/workflows/s3-backup.yml, .github/workflows/scripts.yml, .github/workflows/terraform-security-scan.yml, .github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, renovate.json
Update comments of pinned Github actions so that renovate is aware of the version
https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
=> fix: use correct renovate comment tag

terragrunt/aws/api/api_gateway.tf, terragrunt/aws/api/certificate.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/route53.tf, terragrunt/aws/hosted_zone/hosted_zone.tf, terragrunt/aws/hosted_zone/inputs.tf, terragrunt/env/production/api/terragrunt.hcl, terragrunt/env/production/env_vars.hcl, terragrunt/env/production/hosted_zone/terragrunt.hcl, terragrunt/env/terragrunt.hcl
Continuing to refactor to make it easier to deploy a staging account
=> refactor: move env specific vars into hcl file

api/Makefile, api/api_gateway/routers/clamav.py, api/assemblyline/assemblyline.py, api/boto3wrapper/wrapper.py, api/clamav_scanner/clamav.py, api/clamav_scanner/common.py, api/clamav_scanner/scan.py, api/storage/storage.py, api/tests/api_gateway/test_clamav_scans.py, api/tests/clamav/test_scan.py, api/tests/storage/test_storage.py
scan-files will now assume a role in the account containing the s3 files to be scanned.
=> feat: assume role to download scan file

api/api_gateway/routers/clamav.py, api/clamav_scanner/scan.py, api/tests/api_gateway/test_clamav_scans.py
Reverts cds-snc/scan-files#115 didn't work
=> Revert "fix: create new thread"

api/api_gateway/__init__.py, api/api_gateway/routers/clamav.py, bin/api_clamav_scan_s3.sh
Background tasks is currently blocking. Refactored to use pythons asyncio and threading depending on how the project is launched.
=> feat: utility to run tasks in background using asynio

terragrunt/aws/api/cloudfront.tf
=> fix: provide viewer certificate

.github/workflows/terraform-security-scan.yml, terragrunt/.checkov.yml, terragrunt/aws/api/cloudfront.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/vpc.tf, terragrunt/aws/api/waf.tf
=> fix: viewer certificate

terragrunt/aws/api/waf.tf
=> fix: change waf scope to cloudfront

terragrunt/aws/api/cloudfront.tf
This will allow authenticated requests to the API to work.
=> fix: pass Authorization header to origin

terragrunt/aws/api/iam.tf, terragrunt/aws/api/locals.tf, terragrunt/aws/api/vpc.tf, terragrunt/aws/api/waf.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/terragrunt.hcl
Send VPC flow logs and WAF ACL logs to the Cloud Based Sensor
satellite bucket.
=> feat: send VPC and WAF logs to CBS

module/s3-scan-object/app.test.js
Add a missing assertion for the `custom:rescan` event.
=> fix: add missing test assertion

api/api_gateway/routers/clamav.py
return scan_id when using the synchronous workflow
=> feat: return scan_id when using sync flow

.github/workflows/build_and_push_staging.yml, .github/workflows/ci_build_containers.yml, .github/workflows/integration_test_staging.yml
Add GitHub Workflows to build, push, deploy and test the Staging
lambda functions.
Also cleans up the CI Docker build workflow to remove the
AWS login.
I'll keep this as draft until Staging is fully operational.
=> feat: staging lambda deploy and test workflows

.devcontainer/devcontainer.json, api/main.py, bin/api_clamav_scan.sh, bin/api_healthcheck.sh
Correlation id was not showing since the lambda event headers were lowercase.
=> fix: match against lowercase

terragrunt/aws/alarms/queries.tf
Update `alarms` module to include Log Insight queries.  This
will make it easier to debug errors for new team members.
* #233
=> feat: add Log Insight queries to Terraform

terragrunt/aws/api/waf.tf
Update the regex pattern set description and patterns.
This was applied locally to test.
* #240 
* #239
=> fix: WAF valid URI path regex

.github/workflows/integration_test_production.yml, .github/workflows/integration_test_staging.yml
Update the integration test workflows to run after Terraform
applies are finished.
=> feat: run integration tests after Terraform apply

terragrunt/aws/scan_queue/state_machine.tf
Update after a `terraform fmt` to pass Terraform plan
action checks.
* #254
=> fix: state machine Terraform formatting

renovate.json
Update the Renovate config to include a label and review checklist.
* cds-snc/platform-core-services#118
=> test: renovate config settings

.github/workflows/terraform-security-scan.yml, renovate.json, terragrunt/.checkov.yml
Update the PR body notes to trim down spacing.  
Also manually updates the `checkov` GitHub action to see if this resolves the Renovate
dependency lookup failure.
* #305 
* cds-snc/platform-core-services#118
=> fix: formatting of PR body notes

renovate.json
Debug the Renovate schedule configuration that is not working as expected.
=> test: renovate schedule PRs at any time

renovate.json
Schedule fix will be applied to the default config.
- #319
=> chore: revert schedule test

terragrunt/aws/api/vpc.tf
Add VPC private endpoints for S3, ECR and CloudWatch logs.  This will keep private subnet traffic within the AWS network.
Also upgrades the VPC module version to get access to the `main_route_table_id` output.
- #348
=> feat: add VPC private endpoints

terragrunt/aws/api/route53.tf
Add a CloudWatch log group with Route53 query logging from resources within the API VPC.
- #351
=> feat: add Route53 dns query logging

terragrunt/aws/s3_scan_object/lambda.tf
Update the Pino logging level to be `warn`.
=> fix: pino logging level

.github/actions/docker-scan/action.yml, .github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml, .github/workflows/ci_build_containers.yml, api/Dockerfile
Update Docker workflows to scan Docker images with Trivy and upload the generated SBOM to the GitHub dependency submission endpoint.
- cds-snc/platform-core-services#140
=> feat: docker dependency scan using Trivy

.github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml, module/s3-scan-object/Dockerfile
Update the Docker scan action with the correct Docker image reference to scan.
- cds-snc/platform-core-services#140
=> fix: reference to Docker image to scan

terragrunt/aws/api/cloudfront.tf
Update the API's CloudFront distribution with CORS configuration.
- #401
- #400 
=> feat: add CORS configuration to CloudFront

terragrunt/aws/api/route53.tf
This will block all DNS queries from the VPC that are not part of the `AllowedDomains` list.
- #425
=> feat: add resolver DNS firewall

.github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml
Update the Docker dependency scan `docker_image` attribute.
=> fix: docker_image attribute on dependency scan

.github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml, .github/workflows/ci_build_containers.yml
Using new version of trivy docker scan action
=> chore: using new version of trivy

.github/workflows/docker_vulnerability_scan.yml
Run a nightly scan for Docker vulnerabilities and publish results to the GitHub Security section of the project.
- cds-snc/platform-core-services#209
=> feat: scheduled docker vulnerability scan

api/requirements.txt
Fix security vulnerability CVE-2022-40897.
- #501
=> fix: upgrade Python setuptools

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
Update the S2 scan object module to allow it to receive S3 event notifications from an SQS queue.  SQS events have the source events nested in their `events.record.body` attribute, so the change just involves extracting the nested S3 event and processing it as if it was a direct S3 event invocation of the function.
This is being done so that we can remove the transport lambda function from onboarded accounts.
- cds-snc/platform-core-services#365
=> feat: add SQS S3 notification event source

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Update the SQS event onboarded accounts to include Notify.
This will have no TF changes as it only applies to production.
=> feat: onboard Notify to s3_scan_object

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Update SQS event accounts to include Forms staging.
There should be no changes as this is a Prod change only.
- cds-snc/platform-core-services#380
=> chore: onboard Forms staging to s3_scan_object

api/bin/entry.sh
Update the API's entry point to check that the secrets were retrieved during init.
=> fix: improve resilience of API lambda init

terragrunt/aws/api/s3.tf
Update the file queue and virus def S3 access log bucket to no longer be marked as critical.
=> fix: update the S3 log bucket critical tag

terragrunt/aws/alarms/athena.tf, terragrunt/aws/alarms/lambda.tf, terragrunt/aws/alarms/sentinel_logging.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/oidc_iam.tf, terragrunt/aws/api/rds.tf, terragrunt/aws/api/route53.tf, terragrunt/aws/api/s3.tf, terragrunt/aws/api/vpc.tf, terragrunt/aws/integration_test/s3_scan_object.tf, terragrunt/aws/s3_scan_object/lambda.tf
Update the version reference for the Terraform modules to be after the module sub-directory.
=> fix: Terraform module reference

terragrunt/aws/api/rds.tf
Update to the latest RDS TF module to export `postgresql` logs to CloudWatch.
=> chore: update to latest RDS TF module

terragrunt/aws/api/lambda.tf
Testing a second instance of the API that can be used with provisioned concurrency for sync scans.
- https://github.com/cds-snc/notification-admin/pull/1767
=> test: add a second instance of the Scan Files API

api/api_gateway/custom_middleware.py, api/tests/api_gateway/test_api.py
Update the CSP to allow the Swagger docs to load.
=> fix: API Swagger CSP directives

catalog-info.yaml
Test adding an API definition to the entity
=> Update catalog-info.yaml w/ API entity

catalog-info.yaml
=> fix: typo on metadata

terragrunt/aws/alarms/sentinel_logging.tf
Update the module to the latest version that uses an SSM parameter to store the Sentinel auth credentials.
=> chore: update Sentinel Forwarder TF module

terragrunt/aws/api/rds.tf, terragrunt/env/production/s3_scan_object/terragrunt.hcl, terragrunt/env/staging/s3_scan_object/terragrunt.hcl
Update the list of Staging SQS account IDs to include a Scratch account.
=> feat: add Scatch account ID to Staging
