.github/workflows/terraform-security-scan.yml, terragrunt/.checkov.yml, terragrunt/aws/api/api_gateway.tf, terragrunt/aws/api/cloudwatch_log.tf, terragrunt/aws/api/ecr.tf, terragrunt/aws/api/iam.tf, terragrunt/aws/api/kms.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/waf.tf, terragrunt/env/common/provider.tf
Integrate lambda with api gateway. Will fix any outstanding confest issues in a subsequent PR's due to the default_tags needing to be removed this cycle and causing opa_check failures even though the tag exists.
=> feat: apigateway lambda integration

.devcontainer/docker-compose.yml, api/api_gateway/routers/scans.py
Scan id is now available before the call to assemblyline
fixes: #9
=> fix: commit scan id before using as metadata

terragrunt/aws/api/iam.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/s3.tf
Required for upcoming file scanning queue. User uploaded files will be saved to S3 and be processed in the background below the CCCS rate limit.
=> feat: file queue and quarantine buckets

terragrunt/aws/api/lambda.tf, terragrunt/env/scan_queue/terragrunt.hcl
Increase lambda timeout to allow time for file I/O and increase polling frequency to reduce calls to AssemblyLine.
Closes #22
=> feat: increase wait times and lambda timeout

terragrunt/aws/api/api_gateway.tf, terragrunt/aws/api/certificate.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/route53.tf, terragrunt/env/api/terragrunt.hcl
- This creates a custom domain name, certificate and DNS "A" record for scan-files.alpha.canada.ca.
- Enables api documentation located at /docs
Closes #25
=> feat: API stage custom domain and certificate

terragrunt/env/common/provider.tf
Pin AWS provider to version 3 in-order to prevent breaking changes.
=> feat: pin terraform to version 3

.github/workflows/generate_sbom.yml
The shared workflow in `security-tools` is being replaced with a
composite action.
* cds-snc/platform-sre-security-support#94
=> fix: switch to generate SBOM composite action

terragrunt/aws/api/oidc_iam.tf
The new version of the OIDC module does not create
the provider by default.  This change will cause it to
be created.
* #65
=> fix: create the OIDC provider

.github/workflows/build_and_push.yml, .github/workflows/ci_build_continers.yml
Perform the ECR Docker image push using the OIDC role.
Also remove the AWS_ACCOUNT variable and hard code the
account ID as these are no longer considered secret.
=> chore: add OIDC auth to the Docker image workflow

renovate.json
Currently by default renovate creates a PR for each dependencyupdate. This PR updates the renovate config to group major and patch dependecy bumps so make it more manageable. Major versions will continue to remain as individual PRs.
=> feat: group major and patch dependency bumps

renovate.json
Excluding Python when minor dependency version updates are grouped.
=> feat: exclude python from being grouped

renovate.json
This new setup should grab the default config from https://github.com/cds-snc/renovate-config. If this works out well, we can add this `renovate.json` to our github templates
=> feat: test out new default config setup

terragrunt/aws/api/lambda.tf
Migrated to using `ssm` and `loadenv` in a previous PR. Majority of lambda envs are no longer required.
=> feat: lambda envs no longer required

api/bin/entry.sh, api/main.py, api/tests/test_main.py
Lambda only allows writes to the `/tmp` folder so the aws ssm parameter `.env` retrieval has been updated
=> fix: write ssm env to /tmp

api/bin/entry.sh, api/main.py, api/requirements.txt, api/tests/test_main.py
`python-dotenv` doesn't work across files. Instead of using a singleton approach i've decided to setup the env in the dockerfile. This will make it more consistent across environments. Code copied from `notification-api` setup.
=> refactor: load envs in entrypoint

terragrunt/aws/api/lambda.tf
For rate expressions any value greater than 1 must be plural
=> fix: schedule expression syntax

terragrunt/aws/api/lambda.tf
ClamAV was unable to run with the default lambda memory size of 256MB. ClamAV uses on average of 1GB of memory. Bumping the memory to 1024 + 256 (original) + 256 (buffer) = 1536.
=> feat: increase memory to account for clamav

api/api_gateway/routers/clamav.py
Adding a extra create_dir since contents in `/tmp` don't persist
=> fix: ensure required dir exists

api/Makefile, api/api_gateway/routers/clamav.py, api/assemblyline/assemblyline.py, api/clamav_scanner/clamav.py, api/clamav_scanner/scan.py, api/tests/api_gateway/test_clamav_scans.py, api/tests/clamav/test_scan.py, api/tests/conftest.py
New endpoint that accepts a s3 object key & sns arn. The scan-files role `arn:aws:iam::806545929748:role/api` will need s3 get permissions.
=> feat: scan files from s3 bucket

.github/workflows/tf_apply.yml, .github/workflows/tf_plan.yml, api/bin/entry.sh, terragrunt/aws/api/iam.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/ssm.tf
Cleanup of items moved to the `ENVIRONMENT_VARIABLE` ssm paramter as well as creating a new parameter to be used to share the api key amongst scan-files services that need it.
=> feat: store the api key in ssm to be shared

api/bin/entry.sh
Instead of individual ssm parameters containing a key/value pairs, setup the `key=` on coldstart.
current: `API_AUTH_TOKEN=foo`
new: `foo`
=> fix: populate env file with key value

.github/workflows/scripts/migrate.sh, api/tests/conftest.py, api/tests/test_main.py, terragrunt/aws/api/iam.tf, terragrunt/aws/api/lambda.tf
The Lambda function is using an IAM role it creates and manages
as part of the module. This change removes the unused IAM role 
and attaches the cross-account assume policy
to the Lambda function.
Also renames the Lambda function from `api` to `scan-files-api`.
=> chore: remove unused scan-files-api IAM role

.devcontainer/Dockerfile, api/clamav_scanner/clamav.py, api/clamav_scanner/scan.py, api/tests/api_gateway/test_clamav_scans.py, api/tests/clamav/test_scan.py
Fix to only retrieve a file reference so that the file can be seek+read when writing to disk.
=> fix: retrieve object ref instead of file

.github/workflows/tf_apply_production.yml, .github/workflows/tf_plan_production.yml, terragrunt/aws/s3_scan_object/ecr.tf, terragrunt/aws/scan_queue/inputs.tf, terragrunt/env/production/s3_scan_object/terragrunt.hcl
The Scan Files AWS account will hold the S3 scan object Lambda container
image in its shared ECR and allow other the Lambda service in other
AWS accounts in the same org to pull and use that image.
This PR creates the ECR and policy to allow the cross-account service access.
=> feat: S3 scan object ECR for Lambda container image

terragrunt/aws/s3_scan_object/ecr.tf
Update the ECR resource policy so that the Docker image can
be successfully pulled by cross-account Lambda service function
creation requests.
=> fix: ECR policy to allow cross-account pulls

terragrunt/aws/s3_scan_object/ecr.tf
Update to allow the Lambda service to pull the image if it's
for a matching function ARN.
Since the `ArnLike` condition has a wildcard for the account, I
tested to ensure that the Lambda function cannot be created
unless the AWS principal is part of our organization.
=> fix: ECR Lambda service IAM policy statement

terragrunt/aws/s3_scan_object/ecr.tf
Update the ECR name to include `module`.
* #122 
=> fix: S3 scan object ECR name

terragrunt/aws/s3_scan_object/ecr.tf
The Terraform module adds the project name as a suffix to the
end of the function name.  This changes allows the creation
of those suffixed functions.
This was applied locally so there should be no plan changes.
=> fix: allow suffixes on the S3 scan object name

terragrunt/aws/api/cloudfront.tf
cloudfront requires the domain name of the s3 bucket instead of it's name
=> fix: use domain name instead of bucket name

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js, module/s3-scan-object/package.json, module/s3-scan-object/yarn.lock
Update the S3 scan object Lambda to load the Scan Files
API key from the given SecretsManager secret ARN.
This will allow all instances of the Lambda to use the same
secret in the Scan Files account.  
Access to this secret is restricted via IAM resources policies to:
* AWS accounts in the Organization; and
* `PrincipalArn` access from the S3 scan object lambda function role ARN.
* #133 
=> feat: retrieve API key from SecretManager

terragrunt/aws/api/waf.tf
Excluding `POST` requests to `/clamav` and `/assemblyline` from WAF rules that contain alot of request body related checks.
=> feat: exclude post to clamav and assemblyline from waf rules

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
Add a `custom:rescan` event source that allows the Lambda function
to retrigger a scan on an existing S3 object.  The expected event
payload is:
```javascript
{
"Records": [{
"eventSource": "custom:rescan",
"s3ObjectUrl": "s3://bucket_name/object_key"
}]
}
```
* Closes #141 
=> feat: add ability to rescan existing S3 objects

api/clamav_scanner/scan.py, api/tests/clamav/test_scan.py
the scan results sns topic will now receive the generated checksum in-order to offer non-repudiation that the scan verdict sent is the result of the file submitted for scanning.
=> feat: send checksum back

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
This provides non-repudiation for the scan verdict since
the object's checksum can be calculated and compared
to the tagged checksum to show it's the same file that
was scanned.
* #144 
=> feat: tag S3 object with scan checksum

api/clamav_scanner/common.py
Update how `AV_SCAN_USE_CACHE` environment variable is read so that
it is treated as a boolean value.
=> fix: treat AV_SCAN_USE_CACHE env var as a boolean

terragrunt/aws/api/lambda.tf
Update the API Lambda function memory to 1,769 MB which is the memory
threshold that provides [1 vCPU to the function](https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html#configuration-memory-console).
During performance testing, this was the configuration that gave the
largest increase in speed compared to total memory allocated.
=> chore: bump API lambda memory to 1769 MB

api/locustfile.py
Update the Locust performance test to read from an `AV_ENDPOINT`
environment variable so that it can be used for Assemblyline and ClamAV
endpoint tests.
* cds-snc/platform-forms-client#853
=> fix: generic scanning endpoint performance test

.devcontainer/docker-compose.yml, api/.env.example, api/Dockerfile, api/bin/entry.sh, api/clamav_scanner/clamav.py, api/clamav_scanner/common.py, terragrunt/aws/api/ecr.tf
The current ClamAV setup is taking ~30 seconds due to ClamAV loading the antivirus definitions in memory. We'll be migrating to use the daemon which will preload the definitions at the start of the container. This should significantly increase scan times since the majority of the 30 seconds was related to loading definitions into memory.
=> feat: use clamav daemon to scan

terragrunt/aws/api/cloudfront.tf, terragrunt/aws/api/route53.tf
Add Route53 health check to keep the Scan Files API lambda warm.
Also updates CloudFront so that the `/healthcheck` path is not
cached.
=> feat: Route53 health check to act as Lambda warmer

api/api_gateway/routers/clamav.py, api/clamav_scanner/clamav.py, api/clamav_scanner/scan.py, api/tests/api_gateway/test_clamav_scans.py
ability to override cache settings via a new query parameter `ignore_cache` when calling the `/clamav` endpoint.
=> feat: on-demand rescan via api parameter

api/clamav_scanner/clamav.py
Update the `is_clamd_running` function to perform the
sockect connection within the `try/catch` block.
Reason being that if the socket cannot be connected to,
we want to return `False` for the check and attempt
to start the ClamAV daemon.
=> fix: move socket connection into try/catch

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
Update the code so that newly created S3 folders are not scanned.
S3 folders can be identified by their trailing `/`.
=> fix: prevent S3 folder objects from being scanned

terragrunt/aws/api/kms.tf, terragrunt/aws/api/lambda.tf
Remove principal for S3 scan object lambda function as it
does not exist yet.
Also increase the Lambda function memory to deal with
OOM process killed exceptions during load testing.
I applied the `api` module change locally to avoid exposing our 
AWS org ID in the plan since it had been marked as not sensitive 
in #165.
* #165 
=> fix: KMS key policy

terragrunt/aws/api/kms.tf, terragrunt/aws/s3_scan_object/lambda.tf
Add `:latest` tag to lambda image URI.
Also updates the KMS key policy to include the lambda
role ARN as a principal.
This was applied locally.
* #165 
* #166 
=> fix: S3 scan object lambda image URI

terragrunt/aws/api/secrets.tf
The KMS key ID for the secret needs to start with `alias`
to properly find the key.
This was applied locally.
* #170
=> fix: reference to KMS key alias

.github/manifests/lambda_api_version, .github/manifests/lambda_s3_scan_object_version, .github/workflows/build_and_push_production.yml, .github/workflows/deploy_lambda_production.yml
Add lambda version manifests that control the Docker 
images that are deployed to Production for the
`scan-files-api` and `s3-scan-object` functions.
Once the Staging environment is setup, the `latest` 
Docker images will always be deployed on push to 
`main` in that account.
=> feat: explicit deploy of lambda functions

.github/workflows/integration_test_production.yml
Update the integration test polling to use a `while` loop instead
of `until`.  Reason for the change is that the exit code of `1` for
the `until` loop's grep command was causing the job step
to exit with an error.
* #177
=> fix: use `while` loop in Lambda integration tests

.github/workflows/tf_apply_production.yml, .github/workflows/tf_plan_production.yml, terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/inputs.tf, terragrunt/aws/alarms/lambda.tf, terragrunt/aws/alarms/sns.tf, terragrunt/aws/api/outputs.tf, terragrunt/aws/integration_test/s3_scan_object.tf, terragrunt/env/production/alarms/terragrunt.hcl
Add a CloudWatch alarm that posts to Slack if the Route53 API
health check is failing.
=> feat: add CloudWatch health check alarm

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, api/api_gateway/api.py, api/api_gateway/custom_middleware.py, api/api_gateway/routers/clamav.py, api/clamav_scanner/clamav.py, api/clamav_scanner/scan.py, api/logger.py, api/main.py, api/requirements.txt, api/tests/clamav/test_clamav.py, api/tests/clamav/test_scan.py, api/tests/conftest.py, api/tests/test_main.py, bin/api_healthcheck.sh
Scan-files now expects a `X-Scanning-Request-Id` header and will use that to create contextual logging. These new loggers will be passed into any method where we'd like to track the lifecycle of a specific `X-Scanning-Request-Id`
=> feat: track scan request lifecycle

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js, module/s3-scan-object/package.json, module/s3-scan-object/yarn.lock
Update to use the `pino` logging lib for the S3 scan object lambda.
This allows for lambda invocation specific parameters like `RequestId`
to be added automatically to all log messages.
* #174
=> feat: use `pino` logging lib for S3 scan object

api/clamav_scanner/clamav.py
Update the logging from the ClamAV daemon startup to log less errors
during the daemon startup.  This is being done so that we can setup
CloudWatch alarms that trigger on unexpected API errors.
Part of this change is to add more log output around failures to get
the daemon's PID so that we can tune the exception handling in the
`get_clamd_pid` method.
=> fix: `ERROR` logs from ClamAV daemon startup

api/clamav_scanner/clamav.py
Update `get_clamd_pid` to treat a non-zero exit code from the
pidof command as expected as this will return `1` in cases where
the `clamd` process is not running.
Failures to start `clamd` will still result in an ERROR logged thanks
to the behaviour of `start_clamd_daemon`:
https://github.com/cds-snc/scan-files/blob/main/api/clamav_scanner/clamav.py#L344
=> fix: treat non-zero pidof command as info

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/inputs.tf, terragrunt/aws/api/outputs.tf, terragrunt/aws/s3_scan_object/outputs.tf, terragrunt/env/production/alarms/.terraform.lock.hcl, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Add alarms for the API and S3 scan object log groups that will post
to the Slack ops channels when `ERROR` severity messages are logged.
=> feat: CloudWatch alarms for `ERROR` logs

terragrunt/aws/alarms/alarms.tf
Update the CloudWatch alarms to use the
`GreaterThanOrEqualToThreshold` operator.
=> fix: use the alarm `>=` comparison operator

api/api_gateway/custom_middleware.py, api/api_gateway/routers/clamav.py, api/main.py
Taking advantage of the logger always containing the scan id, so it's no longer necessary to inject into the context object.
=> fix: use log to retrieve scanning id when needed

module/s3-scan-object/app.js
Update to use `correlation_id` in the S3 scan object logs to be consistent
with how request ID is being logged by the API.
* #196
=> fix: use `correlation_id` in the S3 scan object logs

.github/workflows/generate_sbom.yml
Update the GitHub workflow to generate an SBOM for the
`s3-scan-object` module dependencies.
=> feat: add SBOM for s3-scan-object module

api/api_gateway/custom_middleware.py, api/tests/api_gateway/test_api.py, terragrunt/aws/api/cloudfront.tf
currently unable to view the /docs endpoint due to the recently introduced CSP. Unfortunately setting `data: 'unsafe-eval'` is required due to the swagger docs using inline svg images. Since this app is api driven and isn't serving user content the risk is low.
=> fix: swagger docs csp violations

terragrunt/aws/api/cloudfront.tf
Update the `api` CloudFront origin config to wait for 60 seconds
before responding with a 504 gateway timeout.
This is required because it can take over 30 seconds (default read
timeout) when a new `api` function execution environment is created
and the ClamAV daemon needs to be started.
=> fix: increase `api` CloudFront read timeout

.github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_staging.yml
Now that the production account has migrated to the same
AWS organization, we no longer need environment specific
org IDs.
=> chore: update to use consistent AWS org ID

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/iam.tf, terragrunt/aws/s3_scan_object/lambda.tf, terragrunt/env/common/common_variables.tf
Update Scan Files to allow it to be used from accounts in both
the new and old AWS org.  Once all accounts are fully migrated
to the new org, we can remove the `aws_org_id_old` variable.
=> fix: allow use from new and old AWS org accounts

api/database/db.py
Update the database connection settings as follows:
1. Explicitly set a pool size of 1 since we use RDS Proxy
which handles our connection pooling.
2. Set pessimistic connection testing with `pool_pre_ping` to check
that a connection is still valid before it is used.
3. Set opptimistic connection testing by pruning any connection that
is older that 25 minutes (since the RDS proxy connection timeout is
30 minutes).
4. Always re-use the last connection used, whic allows the RDS proxy
connection settings to be applied.
* Closes #226
=> fix: database connection settings

.devcontainer/docker-compose.yml, api/requirements_dev.txt
Update the `api` service to mount the ClamAV virus definitions
in the expected location.  This makes it easier to get the
local dev environment setup.
Also updates a dev dependency to fix a Python dependency
resolution issue.
=> fix: mount ClamAV defs in API container

module/s3-scan-object/app.test.js, module/s3-scan-object/package.json, module/s3-scan-object/yarn.lock
The `aws-sdk-client-mock` v2 update moves the Jest matchers into their own
`aws-sdk-client-mock-jest` package which has been added.
=> chore: update to aws-sdk-client-mock v2

terragrunt/aws/api/route53.tf, terragrunt/aws/api/waf.tf
Update the WAF ACL to block the following traffic:
- Any requests from outside North America.
- Any requests that do not match a valid API path.
- More than 2,000 requests in a 5 minute period from an IP address.
Also updates Route53 health checks to only run from North
American regions so they are not blocked by the WAF rules.
* #239
=> feat: tighten WAF ACL rules

terragrunt/aws/alarms/dashboard.tf, terragrunt/aws/alarms/dashboards/ops.json, terragrunt/aws/alarms/inputs.tf, terragrunt/aws/api/outputs.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Add a dashboard that includes metrics for CloudFront,
Lambda, Firewall, CloudWatch Alarm status and any
recent errors logged.
* #234
=> feat: add Ops CloudWatch dashboard

terragrunt/aws/alarms/dashboards/ops.json
Update the Ops CloudWatch dashboard with database metrics.
There should be no changes as this was clickops'd to create the layout.
* #234
=> feat: add database metrics to Ops dashboard

terragrunt/aws/alarms/athena.tf, terragrunt/env/staging/alarms/.terraform.lock.hcl
Update the Athena queries to use a new `logs` workgroup
as the `primary` workgroup already exists by default in the account.
This will allow us to add more workgroups in the future to segment
workloads and query types.
Also updates the Staging lock file with the new version constraints
and modules.
This was applied locally to test.
* #260 
* #253
=> fix: create a new Athena `logs` workgroup

terragrunt/aws/api/rds.tf
Upgrade the DB to 11.16, which has an upgrade path to 14.3.  Also
upgrades the `rds` Terraform module so that DB engine upgrades
can be applied immediately rather than during the maintenance window.
A manual DB snapshot has been taken.
=> chore: upgrade DB to postgres 11.16

terragrunt/aws/api/rds.tf
Upgrade to Postgres version 14.3 as this is the highest
upgrade target available to us from 11.16.
* #277
=> chore: upgrade RDS postgres to 14.3

terragrunt/.checkov.yml, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/waf.tf, terragrunt/env/production/api/terragrunt.hcl, terragrunt/env/staging/api/terragrunt.hcl
Update the WAF ACL rules to make it possible to turn them all on
or off with a single boolean variable.
This will be used for testing only and the `enable_waf` variable
should be kept `true` for day-to-day use of the service.
* #274
=> feat: add WAF ACL rule toggle

api/clamav_scanner/clamav.py, terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/inputs.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Add a CloudWatch alarm for API warnings and update the `is_clamd_running` function to log a warning when it cannot connect to the socket.
The reason for this is because returning `False` from this function is an expected state, and we only want to catch cases where it is continually occurring within a short period.
* #299 
* cds-snc/platform-core-services#119
=> feat: create API CloudWatch warning alarm

renovate.json
The newline is properly handled by Renovate's handlebars template and creates the expected line break.
* cds-snc/platform-core-services#118
=> fix: update prBodyNotes to use newline

renovate.json
This is now included in the org default Renovate config.
* cds-snc/renovate-config#9
* cds-snc/platform-core-services#118
=> chore: remove `prBodyNotes`

terragrunt/.checkov.yml
Update the checkov skip comment for `CKV2_AWS_32` as a false-positive since the API's CloudFront distribution already includes a secure header policy for both the default and ordered cache behaviour blocks.
* Closes #305
=> chore: update checkov skip comment

terragrunt/env/production/api/terragrunt.hcl
Update prod to mark the OIDC provider as already existing in the account.  This is because the prod account has now migrated to the new Org with a default OIDC provider created by the migration.
There should be no change for this PR.
- #312
=> fix: set prod OIDC provider to exists

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/iam.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/secrets.tf
Update Terraform to include the creation of the `ENVIRONMENT_VARIABLES`
ParameterStore used to configure the API.
Non-sensitive values have been moved into the API lambda function's
environment variables.
* #311
=> feat: create API config environment variables

terragrunt/aws/api/vpc.tf
Add VPC private endpoints for SNS and STS AWS services.
- #354 
- #348
=> fix: add SNS and STS VPC private endpoints

terragrunt/aws/api/lambda.tf, terragrunt/aws/s3_scan_object/lambda.tf
Update the API and S3 object module logging level to `error` to reduce the number of CloudWatch logs being created.
=> chore: change logging level to `error`

terragrunt/aws/api/lambda.tf, terragrunt/aws/s3_scan_object/lambda.tf
We need logging for `WARNING` level logging as well.
=> fix: allow warning logs as well

api/database/db.py
Update the SQLAlchemey database engine to only have a single pool connection. We are using RDS proxy, which handles connection pooling for us.
- #226
=> test: single pool connection

terragrunt/aws/api/vpc.tf
Update the VPC to only have a single NAT gateway
in non-prod environments.
- #373
=> chore: use a single NAT gateway

.github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/waf.tf
Update the WAF ACL to allow Azure US East CIDR ranges through.  These are currently being misidentified as originating in Germany and being blocked by the geolocation match rule.
- #392
=> fix: add IP allowlist to WAF ACL

terragrunt/aws/api/waf.tf
Update the IP set to be in `us-east-1` and have the correct scope for CloudFront.
- #393 
- #392
=> fix: IP set region for CloudFront

.github/workflows/dast_vulnerability_scan.yml
Add a workflow that uses [PortSwigger's Dastardly](https://portswigger.net/burp/dastardly) to run a DAST vulnerability scan after new deployments to Staging and Prod.
=> feat: add DAST vulnerability scan

terragrunt/aws/api/lambda.tf
Update the CORS headers to only allow requests from self and the API endpoint HTTP methods.
=> fix: tighten CORS headers

terragrunt/aws/api/lambda.tf
Update the CORS allowed methods to be an array of items instead of a single string.
- #397 
=> fix: CORS allowed methods

terragrunt/aws/api/lambda.tf
`OPTIONS` method is not supported by AWS.
=> fix: replace unsupported method

terragrunt/aws/api/cloudfront.tf
Access control headers are required when allow credentials is true.
⚠️ This was applied locally to test.
- #402
=> fix: update CloudFront CORS to include headers

.github/workflows/dast_vulnerability_scan.yml, terragrunt/aws/api/cloudfront.tf, terragrunt/aws/api/lambda.tf
Remove all CORS headers from requests.  These are not required
by the API or the OpenAPI `/docs` endpoint.
Also updates Dastardly workflow to only run after API deployments.
Terraform changes were applied locally to test.
- #400
=> fix: remove all CORS configuration

terragrunt/aws/api/route53.tf
Update the priority so that it is between 100 and 9900.  Error received on last TF apply was:
```
Error: error creating Route 53 Resolver DNS Firewall rule group association:
ValidationException: [RSLVR-02017] The priority value you provided is reserved.
Provide a number between "100" and "9900"
```
- #425
=> fix: DNS firewall VPC association priority

terragrunt/aws/api/route53.tf
Update the domain list to use the top level `amazonaws.com` domain since many of the service domains are CNAMEs referencing other AWS controlled domains which are getting blocked with our current specific service domain list.
This was applied locally to test.
- #425
=> fix: use `.amazonaws.com.` domain in domain list

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/alarms/inputs.tf, terragrunt/aws/alarms/sentinel_logging.tf
This PR adds a CloudWatch Log subscription to send suspicious scan verdicts to Sentinel.
=> feat: Send scan verdict output to Sentinel

api/clamav_scanner/clamav.py, api/clamav_scanner/scan.py, api/tests/clamav/test_scan.py
Update the ClamAV scanner logging so that it warns when a non-clean verdict is returned.
- #430
=> fix: warn when non-clean scan verdicts

.devcontainer/devcontainer.json, .github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/route53.tf
Update the resolver DNS query logging and firewall to use the new Terraform module.
Also bumps to the latest versions of Terraform and Terragrunt.
State migration was performed locally.
- #425
=> chore: switch to resolver DNS Terraform module

renovate.json
Update the renovate config to test grouping of Docker and GitHub Action dependency updates.
- GitHub actions will have all updates grouped in a single PR, included major updates.
- Docker images will have all updates group except for major updates.
- cds-snc/platform-core-services#182
=> test: renovate config to group Docker and GitHub

renovate.json
Update the Renovate Docker config to only group minor, patch, pin and digest updates.
This will keep major version upgrades separate in their own PRs.
- cds-snc/platform-core-services#182
=> fix: do not group major Docker upgrades

renovate.json
Update the Renovate Docker group package rule to use the `separateMultipleMajor` config item, which is a more elegant way of achieving the desired behaviour:
1. Group all non-major Docker updates into a single PR.
2. Create a single PR for each major Docker update.
- cds-snc/platform-core-services#182
=> fix: Renovate Docker separate multiple major

module/s3-scan-object/Dockerfile
Update the S3 scan object Docker image to explicitly set its cache directory to a folder in `/tmp` so that Lambda can write to it.
- Closes #447
=> fix: S3 scan object's npm cache directory

api/Dockerfile, terragrunt/aws/alarms/alarms.tf
The AWS cli is needed to retrieve the API's secret env vars.
Also updates the API and S3 scan object CloudWatch alarm filters to capture the `error` string.
- #370 
- #454
=> fix: add AWS cli back to image

renovate.json
Update the Renovate config to group all non-major Docker image and GitHub action updates.
Major has been removed because it's leading to scenarios where a major update cannot be easily ignores as it's being grouped with minor/patch updates we want to take.
- cds-snc/platform-core-services#182
=> fix: adjust Renovate Docker and GH action groups

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/api/route53.tf
Update the resolver DNS to include the ClamAV CloudFlare download URL that the `database.clamav.net` CNAME.
Also update the CloudWatch alarm filter to capture `failed` log messages.
- #462
=> fix: add ClamAV CloudFlare download URL

api/conf/freshclam.conf
Update the freshclam config to compress its local database. This should help us gain some space to fit within the Lambda `/tmp` 512MB size limit.
- #460
=> feat: compress freshclam vuln database

renovate.json
This grouping config has now been added to the org's default Renovate config.
- cds-snc/renovate-config#28
- cds-snc/renovate-config#29
=> chore: remove redundant Renovate config

terragrunt/aws/alarms/queries.tf
Update the CloudWatch Log Insights error queries to be case-insensitive.  Also add checks for the string `FAILED`.
- #472
=> fix: case-insensitive log insights error queries

api/clamav_scanner/clamav.py
Before performing a freshclam update, check how much space is available.  This is being done to troubleshoot intermittent problem we see downloading the daily virus definition updates.
- #472
=> test: check freshclam available space

api/clamav_scanner/clamav.py, terragrunt/aws/api/lambda.tf
This will fix errors being raised by `freshclam` when it attempts to update the virus definitions and a `.cdiff` patch file does not exist.
Also removes the size debugging code from the API function code.
- Closes #472 (second time's the charm)
=> fix: increase API function's ephemeral storage

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/inputs.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Update the ClamAV scan verdict alarm to only trigger for scan verdicts that are `unknown` or `unable_to_scan`.
The reason for this change is because malicious/suspicious verdicts are expected and should be handled by the service downstream that is using scan files.
=> fix: update scan verdict alarm to unknown

terragrunt/aws/s3_scan_object/lambda.tf
The S3 scan object's reserved concurrency was set too low and was causing function throttles.
- #547
=> fix: remove reserved concurrency from function

terragrunt/aws/s3_scan_object/lambda.tf
Update the s3_scan_object Lambda functions timeout to fix issues that were happening when large files were being scanned.
- #550
=> fix: increase s3_scan_object timeout to 5 mins

terragrunt/aws/api/outputs.tf, terragrunt/aws/s3_scan_object/inputs.tf, terragrunt/aws/s3_scan_object/lambda.tf, terragrunt/env/production/s3_scan_object/terragrunt.hcl, terragrunt/env/staging/s3_scan_object/terragrunt.hcl
Update the S3 scan object lambda function to invoke the scan file API using its function URL.
This will bypass CloudFront and avoid any timeouts related to slow response times from the API which will happen under heavy load.
- #553
=> fix: invoke scan files API via its function url

api/database/db.py
Update the healthcheck so that it works with SQLAlchemy 2.x.
Error message that we're getting:
```
Textual SQL expression 'SELECT version_num FROM a...' should be explicitly declared as text('SELECT version_num FROM a...')
--
```
- #573
=> fix: healthcheck query

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js, terragrunt/aws/api/lambda.tf, terragrunt/aws/s3_scan_object/lambda.tf
Update how the SecretManager API key is retrieved to only occur once during the first cold start's handler invocation.
Previously a Promise was created during function init and then resolved on the first handler call.  The problem this created is that occasionally we would get `InvalidSignatureExceptions` when the handler was executed more than 5 minutes after the initial promise creation.
This PR also increases the lambda function's resources and adds more debug logging.
- cds-snc/platform-core-services#355
- aws/aws-sdk-js-v3#4429
=> fix: initialize S3 scan object config in handler

terragrunt/aws/api/route53.tf, terragrunt/aws/api/waf.tf
Reverts cds-snc/scan-files#605.  Having the extra health check regions is not solving the concurrency problem.
=> Revert "fix: Route53 healthcheck all regions"

terragrunt/aws/api/lambda.tf, terragrunt/aws/integration_test/s3_scan_object.tf, terragrunt/aws/s3_scan_object/lambda.tf
Revert the API and S3 scan object functions to their original memory resource values.  
The increased memory and vCPU is not having any impact over `clamd` init time.
- cds-snc/platform-core-services#358
=> revert: lambda function resource increase

bin/s3_scan_object_performance.sh
Add a script that generates and uploads files to an `s3_scan_object` onboarded account.  The script can be used to test the async scanning under load and roughly measure the time required to finish all scans.
- cds-snc/platform-core-services#365
- cds-snc/platform-core-services#368
=> feat: add s3_scan_object async performance test

module/s3-scan-object/app.js, terragrunt/aws/integration_test/s3_scan_object.tf, terragrunt/aws/s3_scan_object/lambda.tf
Add more log statements to `s3_scan_object` and change from debug to info.  This will remove the third party dependency debug log statements from our logs.
Also update the integration test to use the new SQS queue version of the `s3_scan_object` Terraform module.
=> fix: add more logging to `s3_scan_object` module

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Add Forms SQS queue as a source for s3_scan_object events.
There should be no change as this is a Prod update only.
- https://github.com/cds-snc/platform-core-services/issues/380
=> chore: onboard Forms to s3_scan_object

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Update the list of onboard app accounts to include "share files".
This will have no TF plan changes as it will only apply against the Production account.
=> chore: onboard "share files" app to scan objects

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Remove the SRE Tools account as the Share Files Securely service is being shutdown.
⚠️ **Note:** there will be no TF plan for this change as it only impacts prod.
- https://github.com/cds-snc/share-files-securely/pull/28
=> chore: remove SRE Tools from SQS scan events

terragrunt/env/production/s3_scan_object/terragrunt.hcl, terragrunt/env/staging/s3_scan_object/terragrunt.hcl
Update the Notify Staging environment to use the Scan Files Staging environment.  
This will isolate Prod from Notify Staging pen and load testing.
- https://github.com/cds-snc/notification-terraform/pull/1053
=> fix: update Notify Staging to use Staging

api/api_gateway/api.py, api/api_gateway/custom_middleware.py, api/bin/entry.sh, api/tests/api_gateway/test_api.py, terragrunt/aws/api/secrets.tf
Update the SSM ParameterStore `ENVIRONMENT_VARIABLES` to include the API auth token.  In testing it was discovered that the SecretManager retrieval is behaving asynchronously so a small percentage of Lambda initializations are missing the correct value.
Also updates the check for an `API_AUTH_TOKEN` to the first section of the API where it is initialized.
=> fix: move API auth token into SSM ParameterStore

terragrunt/env/production/s3_scan_object/terragrunt.hcl
Remove the event listeners for the Forms scan files SQS queues.
This will have no TF plan changes as it only applies to production.
=> chore: remove Forms scan files events

module/s3-scan-object/Dockerfile, terragrunt/aws/api/lambda.tf, terragrunt/aws/s3_scan_object/lambda.tf
Upgrade the Node base image being used as this contains fixes that may help with the `ERR_SOCKET_CONNECTION_TIMEOUT` errors seen recently.
Increase the number of retries the AWS SDKs will perform when they receive a failure
response from an AWS service:
https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html
- https://github.com/cds-snc/scan-files/issues/690
=> chore: bump s3_scan_object to node:20.11.0

terragrunt/env/production/s3_scan_object/terragrunt.hcl, terragrunt/env/staging/s3_scan_object/terragrunt.hcl
linked to https://github.com/cds-snc/forms-terraform/pull/611
- Enable file scanning for both Staging and Production environments on GC Forms
=> feat: enable file scanning for both Staging and Production environments on GC Forms

terragrunt/aws/api/cloudfront.tf, terragrunt/aws/api/iam.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/moved.tf, terragrunt/aws/api/outputs.tf, terragrunt/env/staging/api/.terraform.lock.hcl
Add provisioned concurrency to the the dedicated sync API lambda function. As part of this change, also refactor the Terraform to avoid the need to duplicate resource blocks for both functions.
=> feat: setup provisioned concurrency

terragrunt/aws/api/lambda.tf, terragrunt/aws/api/moved.tf
Update the API's provisioned Lambda function to publish a version. This is required by provisioned concurrency.
=> fix: publish a version of the provisioned function

terragrunt/aws/api/lambda.tf
Update the api-provisioned function URL to reference the `latest` alias that has provisioned concurrency setup.
=> fix: add function URL qualifier

terragrunt/aws/api/lambda.tf
Update the default async Scan Files API function URL to not have a qualifier specified.
=> fix: omit qualifier for async Scan Files API function

terragrunt/aws/api/cloudfront.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/locals.tf, terragrunt/aws/api/moved.tf, terragrunt/aws/api/outputs.tf, terragrunt/aws/api/route53.tf
Add a CloudFront distribution and WAF association for the provisioned concurrency version of the Scan Files API.
=> feat: setup `sync.scan-files.alpha.canada` domain

.github/workflows/build_and_push_staging.yml, .github/workflows/deploy_lambda_production.yml
Update the GitHub workflow to wait until the provisioned API has been updated before updating its alias.
Update the healthcheck step with the new `sync` URL.
=> fix: update provisioned API's alias

terragrunt/aws/alarms/inputs.tf, terragrunt/aws/api/outputs.tf, terragrunt/env/staging/alarms/terragrunt.hcl, terragrunt/env/staging/s3_scan_object/terragrunt.hcl, terragrunt/env/staging/scan_queue/terragrunt.hcl
Update the outputs so that the sync function values are also made available to dependencies.  As part of this change, the original function's outputs were renamed to make it clear which function they referenced.
=> feat: add `api` module outputs for the provisioned Lambda function

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/dashboards/ops.json, terragrunt/aws/alarms/inputs.tf, terragrunt/aws/alarms/shield_advanced.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/production/s3_scan_object/terragrunt.hcl, terragrunt/env/production/scan_queue/terragrunt.hcl
Add CloudWatch alarms for the provisioned API lambda function.
Update the production `terragrunt.hcl` files with the new `api` outputs.
=> feat: add alarms for the provisioned API function

terragrunt/env/production/scan_queue/terragrunt.hcl, terragrunt/env/staging/scan_queue/terragrunt.hcl
Update the state mock commands so that the module plans properly when new mock outputs are added.
=> fix: update scan_squeue terragrunt mock commands

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf
Update the API's CloudWatch error and warning alarms to no longer trigger if there is a missing update patch.
This is caused by the target ClamAV update server not having a patch available yet and will resolve on its own.
- https://github.com/cds-snc/scan-files/issues/901
=> chore: suppress missing patch CloudWatch alarms

terragrunt/aws/alarms/locals.tf
Add the missing `WARNING` token from the API's warning CloudWatch alarm metric filter.
- #902 
- https://github.com/cds-snc/scan-files/issues/901
=> fix: add missing `WARNING` token to API alarm

terragrunt/aws/alarms/locals.tf
Update the API CloudWatch warning metric filter to ignore messages that there are no metrics to publish.
=> chore: suppress AWS Lambda Powertools metrics warning

api/Dockerfile, api/requirements.txt
Update Python, Alpine and ClamAV to fix the issue with downloading the latest virus definition bytecode patch.
- #901
=> fix: update to Python 3.11, Alpine 3.19 and latest ClamAV

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf
Update the API CloudWatch metric names to create a metric for each API function.
Also removes the skip filter on the missing database patch.
=> fix: API metric error names

terragrunt/aws/alarms/alarms.tf
Update the `Error`, `Warning` and `Unable to scan` CloudWatch metrics so that their `metric_transformation.name` is also updated to include the API name.
=> fix: update CloudWatch metric_transformation name

terragrunt/aws/api/lambda.tf
Update the API to no longer attempt to use cached scan results.  This is because the feature is not proving useful for the Notify use case where most attachments are unique.
Additionally during heavy Notify sends, the cache result lookup is causing database connection exhaustion errors.
=> fix: disable scan result cache check

module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
Update the s3-scan-object module to no longer tag objects with an `in_progress` scan status.  We have started seeing race conditions where the `in_progress` tag is overwriting final scan status tags.
Going forward, scan metadata without an `av-status` will be considered an in progress scan.
- https://github.com/cds-snc/platform-core-services/issues/585
=> fix: remove `in_progress` stan status tag

module/s3-scan-object/README.md, module/s3-scan-object/app.js, module/s3-scan-object/app.test.js
Update the `s3-scan-object` module so that in progress S3 object tags are no longer added.  These have been removed because in rare cases we were seeing race conditions where the in progress tagging operation overwrote the scan complete tags.
This occurs because S3 tag operations always replace all tags on an object with the new TagSet in the request.
- https://github.com/cds-snc/platform-core-services/issues/585
=> fix: remove in progress S3 objec tags

api/clamav_scanner/clamav.py, api/clamav_scanner/common.py, api/tests/clamav/test_scan.py
Update the ClamAV scan so that Potentially Unwanted Apps (PUA) subcategories can be excluded.
Currently this is not possible with the ClamAV configuration and we are seeing cases where legitimate Government of Canada PDFs that contain JavaScript are being flagged as containing PUAs.
- https://github.com/cds-snc/notification-planning/issues/1636
- [**ClamAV PUAs**](https://docs.clamav.net/faq/faq-pua.html)
=> fix: add ability to suppress PUA findings

.github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml, .github/workflows/docker_vulnerability_scan.yml
Update to the latest scan/generate SBOM actions and provide our own Trivy DB repository URL, which is defined as an organizational variable.
This is being done to address the rate limiting errors we're intermittently getting using Trivy's default public DB repository.
- https://github.com/cds-snc/platform-core-services/issues/597
=> fix: update to latest Docker scan and generate SBOM actions

catalog-info.yaml
The API definition is a json file so Backstage needs to know it needs to parse it vs the definition being the actual definition.
Source: https://backstage.io/docs/features/software-catalog/descriptor-format/#substitutions-in-the-descriptor-format
=> fix: use substitution for API definition ref

catalog-info.yaml
After testing with a different repo, using $text instead of $json seems to be working to parse the content of the file.
=> fix: use $text substitutor

terragrunt/aws/api/lambda.tf, terragrunt/aws/s3_scan_object/lambda.tf
Update the logging levels to save on CloudWatch costs.
=> fix: change logging level for warnings and above

terragrunt/aws/alarms/sns.tf
Add a Customer Managed Key to encrypt the CloudWatch alarm SNS topics.
This is required to satisfy the SSC Config Conformance pack guardrails.
- https://github.com/cds-snc/platform-core-services/issues/787
=> fix: encrypt SNS topics with CMK
